### ISSUE TITLE
pvdata 

### ISSUE THREAD

**Issue by AnduriI** [datenschuft/SMA-EM#54] opened 2021-04-27 12:17 UTC
I tried to activate my inverters to read their data. Using pvdata I get an error which I think means it could not detect the device class.
```
mqtt: ssl disabled
mqtt: sma-em topic SMA-EM/status/3007888915 data published 14:07:26:{"pconsume": 0.0, "psupply": 4976.7, "pvsum": 0, "pusage": -4976.7, "pvdaily": 0, "timestamp": 1619525246.2889485}
2021-04-27 14:07:31: Connection not possible. Check settings or connection.
Daemon: Exception occured
Traceback (most recent call last):
  File "./sma-daemon.py", line 139, in run
    featurelist[featurenr]['feature'].run(emparts,featurelist[featurenr]['config'])
  File "/root/smaemd/features/pvdata.py", line 91, in run
    mdata = get_pv_data(host, int(port), int(modbusid), relevant_registers)
UnboundLocalError: local variable 'relevant_registers' referenced before assignment

mqtt: ssl disabled
mqtt: sma-em topic SMA-EM/status/3007888915 data published 14:07:32:{"pconsume": 0.0, "psupply": 4946.7, "pvsum": 0, "pusage": -4946.7, "pvdaily": 0, "timestamp": 1619525252.28233}
```
Seems to me as if https://github.com/datenschuft/SMA-EM/blob/95bac74b1f47f706041310ddd24b8104b3d7a496/features/smamodbus.py#L409 would not return a propper answer, but I have no idea why or what it returns.
Maybe @sellth can help, as he is the one who updated compatibility to battery inverters (thanks for that, I will connect my sunny boy storage as soon as the others are working)

Best regards,
Anduril

**Comment by sellth** [comment] 2021-04-27 13:51
Maybe your inverter is not in the [DeviceID list](https://github.com/datenschuft/SMA-EM/blob/95bac74b1f47f706041310ddd24b8104b3d7a496/features/smamodbus.py#L61-L390), could you maybe share the model? Unfortunately this list is not complete and only updated as needed. If you set the pv_debug config value to 2, you should also get this error message: `pv: unknown device class; skipping`

**Comment by AnduriI** [comment] 2021-04-27 14:43
as you expected with debug=2 I see that error, but with connection issues before.
```
config
import mqtt.py
mqtt: feature enabled
import pvdata.py
pvdata: feature enabled
mqtt: ssl disabled
mqtt: sma-em topic SMA-EM/status/3007888915 data published 16:37:48:{"pconsume": 0.0, "psupply": 3153.1, "pvsum": 0, "pusage": -3153.1, "pvdaily": 0, "timestamp": 1619534268.1959696}
2021-04-27 16:37:48: Connection not possible. Check settings or connection.
pv: unknown device class; skipping
Daemon: Exception occured
Traceback (most recent call last):
  File "./sma-daemon.py", line 139, in run
    featurelist[featurenr]['feature'].run(emparts,featurelist[featurenr]['config'])
  File "/root/smaemd/features/pvdata.py", line 91, in run
    mdata = get_pv_data(host, int(port), int(modbusid), relevant_registers)
UnboundLocalError: local variable 'relevant_registers' referenced before assignment
```
I have a Sunny Boy 5.0 and Sunny Boy 4.0 installed together with a Sunny Boy Storage 6.0. Are those already added?

**Comment by sellth** [comment] 2021-04-27 17:00
Ok, SB5.0 & 4.0 are actually not on the list, but I've added them in https://github.com/datenschuft/SMA-EM/pull/55. This is probably not the cause of your problem though. 

As you pointed out, the get_device_class function fails to get a response from your inverter. This could be as simple as having the wrong IP address in your config. Unfortunately the connection check for the modbus client appears to be non-functional atm, which I fixed in https://github.com/datenschuft/SMA-EM/pull/56.

If you know your way around the python console, you could try manually connecting using the pymodbus library (just copy the relevant lines from get_device_class). Either way, maybe check the device IPs in your config file.

**Comment by AnduriI** [comment] 2021-04-27 17:28
well I know a little about python and console...
The IPs are correct, no doubt. I checked them in my fritzbox router.
I imported to python and tried `client.connect`, always returning false.
As I first accessed the websites of my inverters to see the data there I had to set a password. Do you also have this? Is that relevant? Anything further I can try and check?

**Comment by sellth** [comment] 2021-04-27 17:35
The password is only for the user interface afaik. You can log in there and check in the "device parameters" if "External communication" > "Modbus" > "TCP server" is enabled.

**Comment by AnduriI** [comment] 2021-04-27 20:20
you are absolutly right. I had a  look and the tcp server is disabled. Is there a way I can enable this as a user or do I have to contact the company that installed them?

**Comment by sellth** [comment] 2021-04-27 20:53
You need to log in as an "installer" to change these settings. In our case, we could set a password for this during the actual installation of the inverter, but it's possible that you have to ask the company. In any case, this TCP server needs to be enabled before you can read-out data via network.

**Closed as completed** 2021-05-01 18:59 UTC

**Comment by AnduriI** [comment] 2021-05-06 15:31
Well I finally got my TCP modbus server enabled and I can see the data in the debug. But one question remains: how do I get all those values to be written to mqtt/influxdb? Especially the batterypercentage and the AC Power would be nice...
```
sma-daemon.py run
config
import mqtt.py
mqtt: feature enabled
import pvdata.py
pvdata: feature enabled
import influxdb.py
influxdb: feature enabled
mqtt: ssl disabled
mqtt: sma-em topic SMA-EM/status/3007888915 data published 16:32:05:{"pconsume": 0.0, "psupply": 11.5, "pvsum": 0, "pusage": -11.5, "pvdaily": 0, "timestamp": 1620311525.1490164}
PV:{'serial': 3006029599, 'Status': 'OK', 'DeviceClass': 'Solar Inverter', 'DeviceID': '9404', 'AC Power': 589, 'daily yield': 1.844674407370955e+16, 'AC_Current': 2.59, 'Grid_Frequency': 49.97, 'DC_Input1_Power': 359, 'DC_Input1_Voltage':294.89, 'DC_Input1_Current': 1.22, 'DC_Input2_Power': 325, 'DC_Input2_Voltage':275.63, 'DC_Input2_Current': 1.18, 'Device_Temperature': 17.7, 'Total_Yield': 3957.125, 'Operating_Time': 12787285, 'Feed-in_Time': 11912348, 'Intermediate_Circuit_Voltage': 340.95, 'Isolation_Resistance': 2944799, 'timestamp': 1620311526.8068488}
PV:{'serial': 3007249188, 'Status': 'OK', 'DeviceClass': 'Battery Inverter', 'DeviceID': 'SBS6.0-10', 'AC Power': 8, 'daily yield': 7.33, 'Device_Temperature':32.0, 'BatteryTemp': 22.6, 'BatteryAmp': 0.054, 'BatteryVolt': 422.53, 'BatteryCharge': 48, 'BatteryState': 'Discharging', 'BatteryHealth': 'OK', 'AC apparent power': 150, 'Grid_Frequency': 49.98, 'Total_Yield': 2340.0, 'Operating_Time': 26121266, 'Feed-in_Time': 11630077, 'timestamp': 1620311526.8068488}
PV:{'serial': 3006244818, 'Status': 'OK', 'DeviceClass': 'Solar Inverter', 'DeviceID': '9403', 'AC Power': 517, 'daily yield': 1.844674407370955e+16, 'AC_Current': 2.259, 'Grid_Frequency': 49.97, 'DC_Input1_Power': 279, 'DC_Input1_Voltage': 235.65, 'DC_Input1_Current': 1.185, 'DC_Input2_Power': 319, 'DC_Input2_Voltage': 270.68, 'DC_Input2_Current': 1.182, 'Device_Temperature': 17.8, 'Total_Yield': 3418.891, 'Operating_Time': 12545848, 'Feed-in_Time': 11582416, 'Intermediate_Circuit_Voltage': 345.42, 'Isolation_Resistance': 2903132, 'timestamp': 1620311526.8068488}
InfluxDB: em data published 16:32:06:[{'measurement': 'SMAEM', 'time': '2021-05-06T14:32:06Z', 'tags': {'serial': 3007888915}, 'fields': {'pconsume': 0.0, 'psupply': 11.5, 'p1consume': 0.0, 'p2consume': 0.0, 'p3consume': 250.1, 'p1supply':89.2, 'p2supply': 172.4, 'p3supply': 0.0, 'pdirectusage': 1094.5, 'pvpower': 1106.0, 'pusage': 1094.5, 'pbattery': 8.0, 'phouse': 1102.5}}]
pv: data skipping
pv: data skipping
pv: data skipping
pv: data skipping
pv: data skipping
mqtt: ssl disabled
mqtt: sma-em topic SMA-EM/status/3007888915 data published 16:32:11:{"pconsume": 0.0, "psupply": 13.4, "pvsum": 1106, "pusage": 1092.6, "pvdaily": 3.68934881474191e+16, "timestamp": 1620311531.1483805}
pv: data skipping
```

**Comment by AnduriI** [comment] 2021-05-06 18:45
For now I solved it by modifying 'features/mqtt.py' and 'features/influxdb.py' similiar to this https://github.com/datenschuft/SMA-EM/blob/9d6a8146b842d4dfeb262b809276a3ec6ea0ace5/features/influxdb.py#L139 and made them both report battery power and charge. Maybe this can be done in a more organized way. Maybe I will post a PR when I have the time to write it in proper code...

**Comment by sellth** [comment] 2021-05-06 19:22
No need for that, it's already in there: https://github.com/datenschuft/SMA-EM/blob/9d6a8146b842d4dfeb262b809276a3ec6ea0ace5/features/influxdb.py#L199-L240

The reason for why this code is skipped for you probably lies within the config.sample. I suspect due to some merge issue the relevant lines were moved to the influxdb2 section. You should paste these under the [FEATURE-influxdb] section in your config file and add all fields you want exported to InfluxDB (e.g. BatteryCharge):

```
#pvdata
pvmeasurement=SMAWR
pvfields=AC Power,grid frequency,DC input voltage,daily yield,total yield,Power L1,Power L2,Power L3
```

As for MQTT, I'm not so sure. Maybe check if it's a similar issue and `pvtopic` is missing. And actually, sometimes the order in which the modules are loaded makes a difference. Go to the [SMA-EM] section and check that pvdata comes before mqtt and influxdb.

**Comment by AnduriI** [comment] 2021-05-07 07:13
thank you very much for pointing this out, but there seems to be a bug in...
when using pvfields I always get an error:
```
InfluxDB: em data published 09:08:04:[{'measurement': 'SMAEM', 'time': '2021-05-07T07:08:04Z', 'tags': {'serial': 3007888915}, 'fields': {'pconsume': 3020.2, 'psupply': 0.0, 'p1consume': 2258.6, 'p2consume': 339.1, 'p3consume': 422.4, 'p1supply': 0.0, 'p2supply': 0.0, 'p3supply': 0.0, 'pdirectusage': 1054.0, 'pvpower': 1054.0, 'pusage': 4074.2, 'pbattery': 0.0, 'phouse': 4074.2, 'battery': 15}}]
Daemon: Exception occured
Traceback (most recent call last):
  File "smaemd/sma-daemon.py", line 139, in run
    featurelist[featurenr]['feature'].run(emparts,featurelist[featurenr]['config'])
  File "/root/smaemd/features/influxdb.py", line 221, in run
    inv.pop(t)
KeyError: 'Device Name'
```
I tried different pvfields, all resulting in the same message. Maybe it's not compatible with influxdb, but only influxdb2?

For mqtt there is no effect of that entry as far as I can see.

**Comment by sellth** [comment] 2021-05-07 08:51
Ok, this is actually another flaw of the config.sample. Sorry for that. 

Please note that the modbus registers "serial", "DeviceID", and "Device Name" are [always used as tags](https://github.com/datenschuft/SMA-EM/blob/9d6a8146b842d4dfeb262b809276a3ec6ea0ace5/features/influxdb.py#L209) in the InfluxDB export and therefore should not be part of the "pvfields" config list. But in your case "Device Name" is actually not queried from the inverter in the first place, because the relevant lines are commented out in the config.sample ([L205](https://github.com/datenschuft/SMA-EM/blob/95bac74b1f47f706041310ddd24b8104b3d7a496/config.sample#L205) & [L238](https://github.com/datenschuft/SMA-EM/blob/95bac74b1f47f706041310ddd24b8104b3d7a496/config.sample#L238)). 

Uncomment those lines and it should work. In L205 "Device_Name" also needs to be changed to "Device Name" (without underscore).

I made some adjustments to the config.sample in PR https://github.com/datenschuft/SMA-EM/pull/57

**Comment by AnduriI** [comment] 2021-05-07 09:57
This works, leading me to the next problem:
```
InfluxDB: em data published 11:52:35:[{'measurement': 'SMAEM', 'time': '2021-05-07T09:52:35Z', 'tags': {'serial': 3007888915}, 'fields': {'pconsume': 7.0, 'psupply': 0.0, 'p1consume': 213.4, 'p2consume': 0.0, 'p3consume': 138.2, 'p1supply': 0.0, 'p2supply': 344.6, 'p3supply': 0.0, 'pdirectusage': 1698.0, 'pvpower': 1698.0, 'pusage': 1705.0, 'pbattery': 2432.0, 'phouse': 4137.0, 'battery': 28}}]
InfluxDBError: 400: {"error":"partial write: field type conflict: input field \"BatteryAmp\" on measurement \"SMAWR\" is type float, already exists as type integer dropped=1"}
InfluxDB failed pv data:11:52:35 [{'measurement': 'SMAWR', 'time': '2021-05-07T09:52:35Z', 'tags': {'serial': 3006029599, 'DeviceID': 'SB5.0-1AV-41', 'Device Name': 'SN: 3006029599'}, 'fields': {'AC Power': 924, 'DC input voltage': 0, 'daily yield': 0, 'total yield': 0, 'Power L1': 0, 'Power L2': 0, 'Power L3': 0, 'Device_Temperature': 18.5, 'BatteryTemp': 0, 'BatteryAmp': 0, 'BatteryVolt': 0, 'BatteryCharge': 0, 'Grid_Frequency': 50.0}}, {'measurement': 'SMAWR', 'time': '2021-05-07T09:52:35Z', 'tags': {'serial': 3007249188, 'DeviceID': 'SBS6.0-10', 'Device Name': 'SN: 3007249188'}, 'fields': {'AC Power': 2432, 'DC input voltage': 0, 'daily yield': 0, 'total yield': 0, 'Power L1': 0, 'Power L2': 0, 'Power L3':0, 'Device_Temperature': 35.6, 'BatteryTemp': 21.6, 'BatteryAmp': 2.962, 'BatteryVolt': 421.88, 'BatteryCharge': 28, 'Grid_Frequency': 50.01}}, {'measurement':'SMAWR', 'time': '2021-05-07T09:52:35Z', 'tags': {'serial': 3006244818, 'DeviceID': 'SB4.0-1AV-41', 'Device Name': 'SN: 3006244818'}, 'fields': {'AC Power': 774, 'DC input voltage': 0, 'daily yield': 0, 'total yield': 0, 'Power L1': 0, 'Power L2': 0, 'Power L3': 0, 'Device_Temperature': 18.5, 'BatteryTemp': 0, 'BatteryAmp': 0, 'BatteryVolt': 0, 'BatteryCharge': 0, 'Grid_Frequency': 50.0}}]
pv: data skipping
pv: data skipping
```
As the BatteryAmp is nothing I hacked into I suppose there is a general problem.

Hery my pvfields in case it helps:
```
#pvdata
pvmeasurement=SMAWR
pvfields=AC Power,DC input voltage,daily yield,total yield,Power L1,Power L2,Power L3,Device_Temperature,BatteryTemp,BatteryAmp,BatteryVolt,BatteryCharge,Grid_Frequency
```
How do the different inverters seperat in the database? I have a grafana running and at the moment it only shows SMAWR, but nothing for the different inverters...

OK found out how to modify my database query:
```SELECT mean("BatteryAmp") FROM "SMAWR" WHERE ("DeviceID" = 'SB4.0-1AV-41') ```

**Comment by sellth** [comment] 2021-05-07 10:09
This is unfortunately a limitation of InfluxDB. Once a field type has been defined by its first value (in your case probably 0, which is an integer) it can't be changed anymore. So when your inverter later reports actual values in float numbers, it results in this error.

I'm looking into how we can coerce field types better in the future, but in the meantime dropping all rows in the SMAWR measurement (that have this field) should fix it.

**Comment by AnduriI** [comment] 2021-05-07 11:52
I dropped the complete measurement SMAWR and restartet with `sma-daemon run`. In the second run its the same as before, but the first one looks different. Is he maybe writing an integer 0 on his own?
```
smaemd/sma-daemon.py run
config
import pvdata.py
pvdata: feature enabled
import influxdb.py
influxdb: feature enabled
import mqtt.py
mqtt: feature enabled
PV:{'serial': 3006029599, 'Status': 'OK', 'DeviceClass': 'Solar Inverter', 'DeviceID': 'SB5.0-1AV-41', 'Device Name': 'SN: 3006029599', 'AC Power': 1001, 'AC_Current': 4.206, 'Grid_Frequency': 50.02, 'DC_Input1_Power': 580, 'DC_Input1_Voltage': 302.9, 'DC_Input1_Current': 1.918, 'DC_Input2_Power': 534, 'DC_Input2_Voltage': 275.7, 'DC_Input2_Current': 1.938, 'Device_Temperature': 18.5, 'Total_Yield': 3967.614, 'Operating_Time': 12828761, 'Feed-in_Time': 11952223, 'Intermediate_Circuit_Voltage': 349.42, 'Isolation_Resistance': 2944162, 'timestamp': 1620388012.027938}
PV:{'serial': 3007249188, 'Status': 'OK', 'DeviceClass': 'Battery Inverter', 'DeviceID': 'SBS6.0-10', 'Device Name': 'SN: 3007249188', 'AC Power': 382, 'Device_Temperature': 41.1, 'BatteryTemp': 21.6, 'BatteryAmp': 0.499, 'BatteryVolt': 419.81, 'BatteryCharge': 33, 'BatteryState': 'Discharging', 'BatteryHealth': 'OK','AC apparent power': 400, 'Grid_Frequency': 50.03, 'Total_Yield': 2348.895, 'Operating_Time': 26197745, 'Feed-in_Time': 11671029, 'timestamp': 1620388012.027938}
PV:{'serial': 3006244818, 'Status': 'OK', 'DeviceClass': 'Solar Inverter', 'DeviceID': 'SB4.0-1AV-41', 'Device Name': 'SN: 3006244818', 'AC Power': 881, 'AC_Current': 3.784, 'Grid_Frequency': 50.02, 'DC_Input1_Power': 456, 'DC_Input1_Voltage': 241.1, 'DC_Input1_Current': 1.89, 'DC_Input2_Power': 525, 'DC_Input2_Voltage': 274.19, 'DC_Input2_Current': 1.918, 'Device_Temperature': 18.5, 'Total_Yield': 3428.104, 'Operating_Time': 12586975, 'Feed-in_Time': 11621744, 'Intermediate_Circuit_Voltage': 342.56, 'Isolation_Resistance': 2904973, 'timestamp': 1620388012.027938}
InfluxDB: em data published 13:46:52:[{'measurement': 'SMAEM', 'time': '2021-05-07T11:46:52Z', 'tags': {'serial': 3007888915}, 'fields': {'pconsume': 0.0, 'psupply': 25.7, 'p1consume': 0.0, 'p2consume': 0.0, 'p3consume': 575.3, 'p1supply':514.7, 'p2supply': 86.4, 'p3supply': 0.0, 'pdirectusage': 1856.3, 'pvpower': 1882.0, 'pusage': 1856.3, 'pbattery': 382.0, 'phouse': 2238.3, 'battery': 33}}]
InfluxDBError: 400: {"error":"field type conflict"}
InfluxDB failed pv data:13:46:52 [{'measurement': 'SMAWR', 'time': '2021-05-07T11:46:52Z', 'tags': {'serial': 3006029599, 'DeviceID': 'SB5.0-1AV-41', 'Device Name': 'SN: 3006029599'}, 'fields': {'AC Power': 1001, 'DC input voltage': 0, 'daily yield': 0, 'total yield': 0, 'Power L1': 0, 'Power L2': 0, 'Power L3': 0, 'Device_Temperature': 18.5, 'BatteryTemp': 0, 'BatteryAmp': 0, 'BatteryVolt': 0, 'BatteryCharge': 0, 'Grid_Frequency': 50.02}}, {'measurement': 'SMAWR', 'time': '2021-05-07T11:46:52Z', 'tags': {'serial': 3007249188, 'DeviceID': 'SBS6.0-10', 'Device Name': 'SN: 3007249188'}, 'fields': {'AC Power': 382, 'DC input voltage':0, 'daily yield': 0, 'total yield': 0, 'Power L1': 0, 'Power L2': 0, 'Power L3': 0, 'Device_Temperature': 41.1, 'BatteryTemp': 21.6, 'BatteryAmp': 0.499, 'BatteryVolt': 419.81, 'BatteryCharge': 33, 'Grid_Frequency': 50.03}}, {'measurement': 'SMAWR', 'time': '2021-05-07T11:46:52Z', 'tags': {'serial': 3006244818, 'DeviceID': 'SB4.0-1AV-41', 'Device Name': 'SN: 3006244818'}, 'fields': {'AC Power': 881, 'DC input voltage': 0, 'daily yield': 0, 'total yield': 0, 'Power L1': 0, 'Power L2': 0, 'Power L3': 0, 'Device_Temperature': 18.5, 'BatteryTemp': 0, 'BatteryAmp': 0, 'BatteryVolt': 0, 'BatteryCharge': 0, 'Grid_Frequency': 50.02}}]
mqtt: sma-em topic SMA-EM/status/3007888915 data published 13:46:52:{"pconsume": 0.0, "psupply": 25.7, "pvsum": 1882, "pusage": 1856.3, "pvdaily": 0, "battery": 33, "pbattery": 382, "timestamp": 1620388012.0591273}
mqtt: sma-em topic SMA-EM/status/3007888915 data published 13:46:57:{"pconsume": 0.0, "psupply": 24.6, "pvsum": 1882, "pusage": 1857.4, "pvdaily": 0, "battery": 33, "pbattery": 382, "timestamp": 1620388017.4147394}
mqtt: sma-em topic SMA-EM/status/3007888915 data published 13:47:03:{"pconsume": 0.0, "psupply": 12.3, "pvsum": 1882, "pusage": 1869.7, "pvdaily": 0, "battery": 33, "pbattery": 382, "timestamp": 1620388023.4122112}
mqtt: sma-em topic SMA-EM/status/3007888915 data published 13:47:09:{"pconsume": 83.1, "psupply": 0.0, "pvsum": 1882, "pusage": 1965.1, "pvdaily": 0, "battery": 33, "pbattery": 382, "timestamp": 1620388029.410889}
PV:{'serial': 3006029599, 'Status': 'OK', 'DeviceClass': 'Solar Inverter', 'DeviceID': 'SB5.0-1AV-41', 'Device Name': 'SN: 3006029599', 'AC Power': 1033, 'AC_Current': 4.238, 'Grid_Frequency': 50.01, 'DC_Input1_Power': 602, 'DC_Input1_Voltage': 308.79, 'DC_Input1_Current': 1.95, 'DC_Input2_Power': 550, 'DC_Input2_Voltage': 273.57, 'DC_Input2_Current': 2.012, 'Device_Temperature': 18.5, 'Total_Yield': 3967.62, 'Operating_Time': 12828782, 'Feed-in_Time': 11952244, 'Intermediate_Circuit_Voltage': 357.23, 'Isolation_Resistance': 2944162, 'timestamp': 1620388032.9954102}
PV:{'serial': 3007249188, 'Status': 'OK', 'DeviceClass': 'Battery Inverter', 'DeviceID': 'SBS6.0-10', 'Device Name': 'SN: 3007249188', 'AC Power': 2534, 'Device_Temperature': 40.5, 'BatteryTemp': 21.6, 'BatteryAmp': 3.097, 'BatteryVolt': 418.98, 'BatteryCharge': 33, 'BatteryState': 'Discharging', 'BatteryHealth': 'OK', 'AC apparent power': 2549, 'Grid_Frequency': 50.02, 'Total_Yield': 2348.899, 'Operating_Time': 26197766, 'Feed-in_Time': 11671050, 'timestamp': 1620388032.9954102}
PV:{'serial': 3006244818, 'Status': 'OK', 'DeviceClass': 'Solar Inverter', 'DeviceID': 'SB4.0-1AV-41', 'Device Name': 'SN: 3006244818', 'AC Power': 903, 'AC_Current': 3.975, 'Grid_Frequency': 50.01, 'DC_Input1_Power': 470, 'DC_Input1_Voltage': 244.88, 'DC_Input1_Current': 1.918, 'DC_Input2_Power': 531, 'DC_Input2_Voltage': 281.76, 'DC_Input2_Current': 1.885, 'Device_Temperature': 18.5, 'Total_Yield': 3428.109, 'Operating_Time': 12586996, 'Feed-in_Time': 11621765, 'Intermediate_Circuit_Voltage': 332.6, 'Isolation_Resistance': 2904973, 'timestamp': 1620388032.9954102}
mqtt: sma-em topic SMA-EM/status/3007888915 data published 13:47:15:{"pconsume": 4.6, "psupply": 0.0, "pvsum": 1936, "pusage": 1940.6, "pvdaily": 0, "battery":33, "pbattery": 2534, "timestamp": 1620388035.4103377}
mqtt: sma-em topic SMA-EM/status/3007888915 data published 13:47:21:{"pconsume": 0.0, "psupply": 53.1, "pvsum": 1936, "pusage": 1882.9, "pvdaily": 0, "battery": 33, "pbattery": 2534, "timestamp": 1620388041.408878}
InfluxDB: em data published 13:47:22:[{'measurement': 'SMAEM', 'time': '2021-05-07T11:47:22Z', 'tags': {'serial': 3007888915}, 'fields': {'pconsume': 0.0, 'psupply': 35.5, 'p1consume': 0.0, 'p2consume': 0.0, 'p3consume': 579.0, 'p1supply':504.8, 'p2supply': 109.7, 'p3supply': 0.0, 'pdirectusage': 1900.5, 'pvpower': 1936.0, 'pusage': 1900.5, 'pbattery': 2534.0, 'phouse': 4434.5, 'battery': 33}}]
InfluxDBError: 400: {"error":"partial write: field type conflict: input field \"BatteryAmp\" on measurement \"SMAWR\" is type float, already exists as type integer dropped=1"}
InfluxDB failed pv data:13:47:22 [{'measurement': 'SMAWR', 'time': '2021-05-07T11:47:22Z', 'tags': {'serial': 3006029599, 'DeviceID': 'SB5.0-1AV-41', 'Device Name': 'SN: 3006029599'}, 'fields': {'AC Power': 1033, 'DC input voltage': 0, 'daily yield': 0, 'total yield': 0, 'Power L1': 0, 'Power L2': 0, 'Power L3': 0, 'Device_Temperature': 18.5, 'BatteryTemp': 0, 'BatteryAmp': 0, 'BatteryVolt': 0, 'BatteryCharge': 0, 'Grid_Frequency': 50.01}}, {'measurement': 'SMAWR', 'time': '2021-05-07T11:47:22Z', 'tags': {'serial': 3007249188, 'DeviceID': 'SBS6.0-10', 'Device Name': 'SN: 3007249188'}, 'fields': {'AC Power': 2534, 'DC input voltage': 0, 'daily yield': 0, 'total yield': 0, 'Power L1': 0, 'Power L2': 0, 'Power L3': 0, 'Device_Temperature': 40.5, 'BatteryTemp': 21.6, 'BatteryAmp': 3.097, 'BatteryVolt': 418.98, 'BatteryCharge': 33, 'Grid_Frequency': 50.02}}, {'measurement': 'SMAWR', 'time': '2021-05-07T11:47:22Z', 'tags': {'serial': 3006244818, 'DeviceID': 'SB4.0-1AV-41', 'Device Name': 'SN: 3006244818'}, 'fields': {'AC Power': 903, 'DC input voltage': 0, 'daily yield': 0, 'total yield': 0, 'Power L1': 0, 'Power L2': 0, 'Power L3': 0, 'Device_Temperature': 18.5, 'BatteryTemp': 0, 'BatteryAmp': 0, 'BatteryVolt': 0, 'BatteryCharge': 0, 'Grid_Frequency': 50.01}}]
mqtt: sma-em topic SMA-EM/status/300
```

**Comment by sellth** [comment] 2021-05-07 12:48
Yeah, what's happening here is the first inverter being queried not returning a value for BatteryAmp since it's not a battery inverter which results in a [0 being put in](https://github.com/datenschuft/SMA-EM/blob/9d6a8146b842d4dfeb262b809276a3ec6ea0ace5/features/influxdb.py#L221) as a default fallback. But 0 is an integer and not a float number, hence the type error once the second query (battery inverter) returns a float number.

Can you try again with this fix? https://github.com/datenschuft/SMA-EM/pull/58

**Comment by AnduriI** [comment] 2021-05-10 08:36
removing the defaultvalue of 0 worked. Thank you very much.

**Comment by AnduriI** [comment] 2021-06-10 09:29
Hey @sellth, another question on pvdata: I got it to also publish the values to mqtt, but it also publishes values for `SMA-PV/status/none` (3 messages every time for my 3 inverters). I think this happens when mqtt is publishing (min_ubdate=5) more often then pvdata is getting them (min_update=20).
It's not a big problem as I can simply ignore posts on that topic, but I don't want to spam my broker...

**Comment by sellth** [comment] 2021-06-10 20:33
I can't really tell how this is a problem as I'm not using mqtt. Couldn't you just increase the min_update value?
